### PR TITLE
Fix all the FSC102 Completed Exercises

### PR DESCRIPTION
**Pull request by kdubau**
With these changes they should build on macOS and Windows both on the command line via MSBuild and also in the IDEs (VS and VSfM).

### CODE REVIEW

**Comment by patridge** [comment]
I still need to test the original in VS2017, but I'm worried it might still not be in a usable state for students.

I downloaded your version and loaded up Exercise 1, Completed, into VS2017 (Stable). It popped up this dialog.

image

I told it to build, but it gave me a build error. 

> Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'SQLitePCL.raw, Version=0.7.1.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
> File name: 'SQLitePCL.raw.dll'
>    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
>    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
>    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	FSharpTodo	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1397

After it completed building, it did add these two lines to the first `<PropertyGroup>` of the fsproj file.

```xml
<SelectedDevice>Nexus5-Api24</SelectedDevice>
<DefaultDevice>Nexus5-Api24</DefaultDevice>
```

**Comment by patridge** [comment]
## More troubleshooting on VS2017

### Update NuGet

After updating all the NuGet packages to the latest, it threw out a dozen+ build errors.

<details>
    <summary>Latest packages.config</summary>
```xml
<package id="FSharp.Core" version="4.2.3" targetFramework="monoandroid44" />
  <package id="sqlite-net-pcl" version="1.4.118" targetFramework="monoandroid44" />
  <package id="SQLitePCL.raw_basic" version="0.8.6" targetFramework="monoandroid44" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.8" targetFramework="monoandroid44" />
  <package id="SQLitePCLRaw.core" version="1.1.8" targetFramework="monoandroid44" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.android" version="1.1.8" targetFramework="monoandroid44" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.android" version="1.1.8" targetFramework="monoandroid44" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Console" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Linq.Queryable" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Net.Requests" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Threading.Tasks.Parallel" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Threading.Thread" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Threading.ThreadPool" version="4.3.0" targetFramework="monoandroid44" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="monoandroid44" />
```
</details>

### Add System.Numerics reference

One of those build errors mentioned I needed to add a reference to System.Numerics. I added that reference, and everything built just fine but wouldn't deploy to an emulator.

### Deploy for debug

I set the solution configuration setting to deploy for debug, and it launched the emulator successfully but stalled on deployment. (The last message in Build output was the call to zipalign, but it was still working on that after several minutes.)

### Retry deployment

I cancelled that deployment and tried again, and all was well!

image

## Summary

We might have to do some hand-updating for the FSC courses to make sure everyone can build them in the various Visual Studios.

**Comment by kdubau** [comment]
That is super odd, the project loaded and built immediately for me. Classic F# though. 😛

**Comment by patridge** [comment]
I started from a new copy of your branch, and it built just fine. Once we set the config to deploy, we should be good, I guess. No idea where that first round of errors came from, unless NuGet puked on the restore process and I didn't notice.

**Pull request merged**
